name: Push Build to Widgetbook Cloud

on:
  push:
    branches:
      - main

jobs:
  push-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build -d

      - name: Build Website
        run: flutter build web -t lib/widgetbook.generator.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Push Build
        run: widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }}